#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSPInventory
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MSPInventory_New")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::MSPInventory.Properties.Settings.Default.MSPInventory_NewConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Activity> Activities
		{
			get
			{
				return this.GetTable<Activity>();
			}
		}
		
		public System.Data.Linq.Table<EquipmentModel> EquipmentModels
		{
			get
			{
				return this.GetTable<EquipmentModel>();
			}
		}
		
		public System.Data.Linq.Table<Equipment> Equipments
		{
			get
			{
				return this.GetTable<Equipment>();
			}
		}
		
		public System.Data.Linq.Table<Item> Items
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
		
		public System.Data.Linq.Table<Location> Locations
		{
			get
			{
				return this.GetTable<Location>();
			}
		}
		
		public System.Data.Linq.Table<Model> Models
		{
			get
			{
				return this.GetTable<Model>();
			}
		}
		
		public System.Data.Linq.Table<Prism> Prisms
		{
			get
			{
				return this.GetTable<Prism>();
			}
		}
		
		public System.Data.Linq.Table<PrismType> PrismTypes
		{
			get
			{
				return this.GetTable<PrismType>();
			}
		}
		
		public System.Data.Linq.Table<Shipping> Shippings
		{
			get
			{
				return this.GetTable<Shipping>();
			}
		}
		
		public System.Data.Linq.Table<Project> Projects
		{
			get
			{
				return this.GetTable<Project>();
			}
		}
		
		public System.Data.Linq.Table<UserRole> UserRoles
		{
			get
			{
				return this.GetTable<UserRole>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Activities")]
	public partial class Activity
	{
		
		private int _ActivityID;
		
		private System.Nullable<int> _EquipmentID;
		
		private System.Nullable<int> _PrismTypeID;
		
		private int _Quantity;
		
		private string _LocationFrom;
		
		private string _LocationTo;
		
		private string _PersonInCharge;
		
		private System.DateTime _DateTimeStamp;
		
		private string _Remarks;
		
		public Activity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ActivityID
		{
			get
			{
				return this._ActivityID;
			}
			set
			{
				if ((this._ActivityID != value))
				{
					this._ActivityID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentID", DbType="Int")]
		public System.Nullable<int> EquipmentID
		{
			get
			{
				return this._EquipmentID;
			}
			set
			{
				if ((this._EquipmentID != value))
				{
					this._EquipmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrismTypeID", DbType="Int")]
		public System.Nullable<int> PrismTypeID
		{
			get
			{
				return this._PrismTypeID;
			}
			set
			{
				if ((this._PrismTypeID != value))
				{
					this._PrismTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationFrom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LocationFrom
		{
			get
			{
				return this._LocationFrom;
			}
			set
			{
				if ((this._LocationFrom != value))
				{
					this._LocationFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationTo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LocationTo
		{
			get
			{
				return this._LocationTo;
			}
			set
			{
				if ((this._LocationTo != value))
				{
					this._LocationTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonInCharge", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PersonInCharge
		{
			get
			{
				return this._PersonInCharge;
			}
			set
			{
				if ((this._PersonInCharge != value))
				{
					this._PersonInCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(100)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EquipmentModels")]
	public partial class EquipmentModel
	{
		
		private int _EquipmentModelID;
		
		private string _Model;
		
		private string _Manufacturer;
		
		public EquipmentModel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentModelID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int EquipmentModelID
		{
			get
			{
				return this._EquipmentModelID;
			}
			set
			{
				if ((this._EquipmentModelID != value))
				{
					this._EquipmentModelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this._Model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manufacturer", DbType="NVarChar(50)")]
		public string Manufacturer
		{
			get
			{
				return this._Manufacturer;
			}
			set
			{
				if ((this._Manufacturer != value))
				{
					this._Manufacturer = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Equipments")]
	public partial class Equipment
	{
		
		private int _EquipmentID;
		
		private string _SerialNo;
		
		private int _EquipmentModelID;
		
		private string _LocationFrom;
		
		private string _LocationTo;
		
		private string _PersonInCharge;
		
		private System.Nullable<System.DateTime> _DateTimeStamp;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _PurchaseDate;
		
		private System.Nullable<System.DateTime> _LastCalibrationDate;
		
		private System.Nullable<System.DateTime> _NextCalibrationDate;
		
		public Equipment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int EquipmentID
		{
			get
			{
				return this._EquipmentID;
			}
			set
			{
				if ((this._EquipmentID != value))
				{
					this._EquipmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this._SerialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentModelID", DbType="Int NOT NULL")]
		public int EquipmentModelID
		{
			get
			{
				return this._EquipmentModelID;
			}
			set
			{
				if ((this._EquipmentModelID != value))
				{
					this._EquipmentModelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationFrom", DbType="NVarChar(50)")]
		public string LocationFrom
		{
			get
			{
				return this._LocationFrom;
			}
			set
			{
				if ((this._LocationFrom != value))
				{
					this._LocationFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationTo", DbType="NVarChar(50)")]
		public string LocationTo
		{
			get
			{
				return this._LocationTo;
			}
			set
			{
				if ((this._LocationTo != value))
				{
					this._LocationTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonInCharge", DbType="NVarChar(50)")]
		public string PersonInCharge
		{
			get
			{
				return this._PersonInCharge;
			}
			set
			{
				if ((this._PersonInCharge != value))
				{
					this._PersonInCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(100)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PurchaseDate
		{
			get
			{
				return this._PurchaseDate;
			}
			set
			{
				if ((this._PurchaseDate != value))
				{
					this._PurchaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCalibrationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCalibrationDate
		{
			get
			{
				return this._LastCalibrationDate;
			}
			set
			{
				if ((this._LastCalibrationDate != value))
				{
					this._LastCalibrationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextCalibrationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NextCalibrationDate
		{
			get
			{
				return this._NextCalibrationDate;
			}
			set
			{
				if ((this._NextCalibrationDate != value))
				{
					this._NextCalibrationDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item")]
	public partial class Item
	{
		
		private int _ItemID;
		
		private string _Name;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _DateTimeStamp;
		
		private string _User;
		
		public Item()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(200)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="VarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Location")]
	public partial class Location
	{
		
		private int _LocationID;
		
		private string _Name;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _DateTimeStamp;
		
		private string _User;
		
		public Location()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(200)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="VarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Model")]
	public partial class Model
	{
		
		private int _ModelID;
		
		private int _ItemID;
		
		private string _Model1;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _DateTimeStamp;
		
		private string _User;
		
		public Model()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this._ModelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int NOT NULL")]
		public int ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Model", Storage="_Model1", DbType="VarChar(100)")]
		public string Model1
		{
			get
			{
				return this._Model1;
			}
			set
			{
				if ((this._Model1 != value))
				{
					this._Model1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(200)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="VarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prisms")]
	public partial class Prism
	{
		
		private int _PrismID;
		
		private int _PrismTypeID;
		
		private int _Quantity;
		
		private string _LocationFrom;
		
		private string _LocationTo;
		
		private string _PersonInCharge;
		
		private System.Nullable<System.DateTime> _DateTimeStamp;
		
		public Prism()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrismID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int PrismID
		{
			get
			{
				return this._PrismID;
			}
			set
			{
				if ((this._PrismID != value))
				{
					this._PrismID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrismTypeID", DbType="Int NOT NULL")]
		public int PrismTypeID
		{
			get
			{
				return this._PrismTypeID;
			}
			set
			{
				if ((this._PrismTypeID != value))
				{
					this._PrismTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationFrom", DbType="NVarChar(50)")]
		public string LocationFrom
		{
			get
			{
				return this._LocationFrom;
			}
			set
			{
				if ((this._LocationFrom != value))
				{
					this._LocationFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationTo", DbType="NVarChar(50)")]
		public string LocationTo
		{
			get
			{
				return this._LocationTo;
			}
			set
			{
				if ((this._LocationTo != value))
				{
					this._LocationTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonInCharge", DbType="NVarChar(50)")]
		public string PersonInCharge
		{
			get
			{
				return this._PersonInCharge;
			}
			set
			{
				if ((this._PersonInCharge != value))
				{
					this._PersonInCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PrismTypes")]
	public partial class PrismType
	{
		
		private int _PrismTypeID;
		
		private string _PrismType1;
		
		public PrismType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrismTypeID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int PrismTypeID
		{
			get
			{
				return this._PrismTypeID;
			}
			set
			{
				if ((this._PrismTypeID != value))
				{
					this._PrismTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="PrismType", Storage="_PrismType1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PrismType1
		{
			get
			{
				return this._PrismType1;
			}
			set
			{
				if ((this._PrismType1 != value))
				{
					this._PrismType1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shipping")]
	public partial class Shipping
	{
		
		private int _ShipID;
		
		private int _ItemID;
		
		private int _ModelID;
		
		private string _SerialNo;
		
		private string _LocationFrom;
		
		private string _LocationTo;
		
		private string _PersonInCharge;
		
		private System.Nullable<System.DateTime> _DateTimeStamp;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _PurchaseDate;
		
		private System.Nullable<System.DateTime> _LastCalibrationDate;
		
		private System.Nullable<System.DateTime> _NextCalibrationDate;
		
		private string _Description;
		
		private decimal _QtyIn;
		
		private decimal _QtyOut;
		
		private string _StationName;
		
		private string _User;
		
		private System.Nullable<int> _ProjectID;
		
		private System.Nullable<int> _LocationID;
		
		public Shipping()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ShipID
		{
			get
			{
				return this._ShipID;
			}
			set
			{
				if ((this._ShipID != value))
				{
					this._ShipID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int NOT NULL")]
		public int ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", DbType="Int NOT NULL")]
		public int ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this._ModelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNo", DbType="NVarChar(50)")]
		public string SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this._SerialNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationFrom", DbType="NVarChar(50)")]
		public string LocationFrom
		{
			get
			{
				return this._LocationFrom;
			}
			set
			{
				if ((this._LocationFrom != value))
				{
					this._LocationFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationTo", DbType="NVarChar(50)")]
		public string LocationTo
		{
			get
			{
				return this._LocationTo;
			}
			set
			{
				if ((this._LocationTo != value))
				{
					this._LocationTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonInCharge", DbType="NVarChar(50)")]
		public string PersonInCharge
		{
			get
			{
				return this._PersonInCharge;
			}
			set
			{
				if ((this._PersonInCharge != value))
				{
					this._PersonInCharge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(100)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PurchaseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PurchaseDate
		{
			get
			{
				return this._PurchaseDate;
			}
			set
			{
				if ((this._PurchaseDate != value))
				{
					this._PurchaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCalibrationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCalibrationDate
		{
			get
			{
				return this._LastCalibrationDate;
			}
			set
			{
				if ((this._LastCalibrationDate != value))
				{
					this._LastCalibrationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextCalibrationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> NextCalibrationDate
		{
			get
			{
				return this._NextCalibrationDate;
			}
			set
			{
				if ((this._NextCalibrationDate != value))
				{
					this._NextCalibrationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyIn", DbType="Decimal(20,0) NOT NULL")]
		public decimal QtyIn
		{
			get
			{
				return this._QtyIn;
			}
			set
			{
				if ((this._QtyIn != value))
				{
					this._QtyIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtyOut", DbType="Decimal(20,0) NOT NULL")]
		public decimal QtyOut
		{
			get
			{
				return this._QtyOut;
			}
			set
			{
				if ((this._QtyOut != value))
				{
					this._QtyOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationName", DbType="VarChar(100)")]
		public string StationName
		{
			get
			{
				return this._StationName;
			}
			set
			{
				if ((this._StationName != value))
				{
					this._StationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="VarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectID", DbType="Int")]
		public System.Nullable<int> ProjectID
		{
			get
			{
				return this._ProjectID;
			}
			set
			{
				if ((this._ProjectID != value))
				{
					this._ProjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationID", DbType="Int")]
		public System.Nullable<int> LocationID
		{
			get
			{
				return this._LocationID;
			}
			set
			{
				if ((this._LocationID != value))
				{
					this._LocationID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Project")]
	public partial class Project
	{
		
		private int _ProjectID;
		
		private string _Name;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _DateTimeStamp;
		
		private string _User;
		
		public Project()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ProjectID
		{
			get
			{
				return this._ProjectID;
			}
			set
			{
				if ((this._ProjectID != value))
				{
					this._ProjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(200)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this._DateTimeStamp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="VarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserRoles")]
	public partial class UserRole
	{
		
		private int _UserRoleID;
		
		private string _UserRoleName;
		
		private int _IsAdmin;
		
		public UserRole()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRoleID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int UserRoleID
		{
			get
			{
				return this._UserRoleID;
			}
			set
			{
				if ((this._UserRoleID != value))
				{
					this._UserRoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRoleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserRoleName
		{
			get
			{
				return this._UserRoleName;
			}
			set
			{
				if ((this._UserRoleName != value))
				{
					this._UserRoleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Int NOT NULL")]
		public int IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this._IsAdmin = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User
	{
		
		private int _UserID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _DisplayName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private int _UserRoleID;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this._DisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRoleID", DbType="Int NOT NULL")]
		public int UserRoleID
		{
			get
			{
				return this._UserRoleID;
			}
			set
			{
				if ((this._UserRoleID != value))
				{
					this._UserRoleID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
